# Generated by Django 2.1.7 on 2019-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('as_performed_by', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
